[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"

[environment]
  NODE_VERSION = "18.19.0" # or 20.11.1 — just make sure it's Node 18+ but with npm 9
  NPM_VERSION = "9.8.1"
